### ISSUE TITLE
Unable to include a package using path starting with application root

### ISSUE THREAD

**Issue by dmitry-solomadin** [RandomEtc/ejs-locals#10] opened 2012-09-06 15:45 UTC
It is very common behaviour that when we use following code:

``` javascript
include("/folder/script")
```

the include function should start search for script in /APP_ROOT/folder/script currently instead of application root it uses current folder.

**Comment by RandomEtc** [comment] 2012-09-06 21:59
Can you post a fuller example and help me understand how this differs from #9? Thanks!

**Comment by RandomEtc** [comment] 2012-09-10 02:37
Closing this, I added some tests for absolute includes in `v0.2.2` and I couldn't reproduce your issue. Please re-open if you're still experiencing this problem!

**Comment by dmitry-solomadin** [comment] 2012-09-17 10:22
Hi,

Please reopen issue. First of all I tried to run tests and 7 of them fail with 500 error, the only common thing between those 7 test is call for "include" function. I tried to run test on pure install. 

Second. Your absolute include test is a bit wrong. You are trying to include partial with absolute path from the root folder and it of course should pass. Just place "with-absolute-include.ejs" into "subfolder" and try to run the test again it would fail because it would look for "locals" partial not from "root/locals" but from "root/subfolder/locals".

Sorry, I cannot write real test because as I stated tests are already failing for me.

**Comment by RandomEtc** [comment] 2012-09-17 17:49
Hmm - it sounds ba that the tests don't work at all. Let's fix that first.

Can you paste the results of `npm test` and `npm ls`? And the version of
node are you using? And what platform?

**Comment by dmitry-solomadin** [comment] 2012-09-18 10:51
Here is `npm test` — http://pastebin.com/n9xUgVqw
Here is `npm ls` — http://pastebin.com/H8A7UVCm
I use mac os x mountain lion, node version is v0.8.7

**Comment by yuri-karadzhov** [comment] 2012-09-19 14:02
I have the same issue. Any updates on it?

I use Linux x86_64 and node v0.8.9

**Comment by RandomEtc** [comment] 2012-09-28 03:23
Sorry for delayed response on this thread. I've re-opened the issue so I don't forget to take a look at why the tests fail, but I haven't figured it out yet.

Did you install from npm, or from git clone?

**Comment by yuri-karadzhov** [comment] 2012-09-28 07:19
I have npm installation.

**Comment by dmitry-solomadin** [comment] 2012-09-28 09:12
I tried both.

**Comment by RandomEtc** [comment] 2012-11-12 05:41
For those still following along with this issue: I just tested with a fresh download of ejs-locals and I'm getting the same errors with the tests. Hopefully I can figure that out this evening.

**Comment by RandomEtc** [comment] 2012-11-12 06:08
AHA.

EJS itself now has `include` functionality which unfortunately overrides the `include` function in `ejs-locals`. This means that EJS can now compose templates by itself which is great.

It also means that the `include` functionality in `ejs-locals` should be removed. Will do.

**Comment by RandomEtc** [comment] 2012-11-12 16:18
Closing this. I have removed `include` from `ejs-locals`. You should be able to use `include` from EJS itself now, and it should be better tested/maintained.

**Closed as completed by RandomEtc** 2012-11-12 16:18 UTC
